export const GERMANY_CITIES = [
  { slug: 'aachen', name: 'Aachen', countryIso: 'de', region: '', areaCodes: ['241'] },
  { slug: 'aglasterhausen', name: 'Aglasterhausen', countryIso: 'de', region: '', areaCodes: ['6262'] },
  { slug: 'aichach', name: 'Aichach', countryIso: 'de', region: '', areaCodes: ['8251'] },
  { slug: 'ainring', name: 'Ainring', countryIso: 'de', region: '', areaCodes: ['8654'] },
  { slug: 'albstadt', name: 'Albstadt', countryIso: 'de', region: '', areaCodes: ['7432'] },
  { slug: 'albstadt-ebingen', name: 'Albstadt-Ebingen', countryIso: 'de', region: '', areaCodes: ['7431'] },
  { slug: 'altlay', name: 'Altlay', countryIso: 'de', region: '', areaCodes: ['654'] },
  { slug: 'alzey', name: 'Alzey', countryIso: 'de', region: '', areaCodes: ['6731'] },
  { slug: 'amberg', name: 'Amberg', countryIso: 'de', region: '', areaCodes: ['9621'] },
  { slug: 'arendsee', name: 'Arendsee', countryIso: 'de', region: '', areaCodes: ['39036'] },
  { slug: 'argenbuhl', name: 'Argenbuhl', countryIso: 'de', region: '', areaCodes: ['7566'] },
  { slug: 'aschaffenburg', name: 'Aschaffenburg', countryIso: 'de', region: '', areaCodes: ['6021'] },
  { slug: 'aschau-im-chiemgau', name: 'Aschau im Chiemgau', countryIso: 'de', region: '', areaCodes: ['8052'] },
  { slug: 'augsburg', name: 'Augsburg', countryIso: 'de', region: '', areaCodes: ['821'] },
  { slug: 'ayl', name: 'Ayl', countryIso: 'de', region: '', areaCodes: ['6581'] },
  { slug: 'backnang', name: 'Backnang', countryIso: 'de', region: '', areaCodes: ['7191'] },
  { slug: 'bad-doberan', name: 'Bad Doberan', countryIso: 'de', region: '', areaCodes: ['38203'] },
  { slug: 'bad-essen', name: 'Bad Essen', countryIso: 'de', region: '', areaCodes: ['5472'] },
  { slug: 'bad-friedrichshall', name: 'Bad Friedrichshall', countryIso: 'de', region: '', areaCodes: ['7136'] },
  { slug: 'bad-hersfeld', name: 'Bad Hersfeld', countryIso: 'de', region: '', areaCodes: ['6621'] },
  { slug: 'bad-homburg-vor-der-hohe', name: 'Bad Homburg vor der Hohe', countryIso: 'de', region: '', areaCodes: ['6172'] },
  { slug: 'bad-honningen', name: 'Bad Honningen', countryIso: 'de', region: '', areaCodes: ['2635'] },
  { slug: 'bad-kissingen', name: 'Bad Kissingen', countryIso: 'de', region: '', areaCodes: ['971'] },
  { slug: 'bad-marienberg', name: 'Bad Marienberg', countryIso: 'de', region: '', areaCodes: ['2661'] },
  { slug: 'bad-mergentheim', name: 'Bad Mergentheim', countryIso: 'de', region: '', areaCodes: ['7931'] },
  { slug: 'bad-munstereifel', name: 'Bad Munstereifel', countryIso: 'de', region: '', areaCodes: ['2253'] },
  { slug: 'bad-neuenahr-ahrweiler', name: 'Bad Neuenahr-Ahrweiler', countryIso: 'de', region: '', areaCodes: ['2641'] },
  { slug: 'bad-oeynhausen', name: 'Bad Oeynhausen', countryIso: 'de', region: '', areaCodes: ['5731'] },
  { slug: 'bad-oldesloe', name: 'Bad Oldesloe', countryIso: 'de', region: '', areaCodes: ['4531'] },
  { slug: 'bad-pyrmont', name: 'Bad Pyrmont', countryIso: 'de', region: '', areaCodes: ['5281'] },
  { slug: 'bad-reichenhall', name: 'Bad Reichenhall', countryIso: 'de', region: '', areaCodes: ['8651'] },
  { slug: 'bad-schonborn', name: 'Bad Schonborn', countryIso: 'de', region: '', areaCodes: ['7253'] },
  { slug: 'bad-teinach-zavelstein', name: 'Bad Teinach-Zavelstein', countryIso: 'de', region: '', areaCodes: ['7053'] },
  { slug: 'bad-vilbel', name: 'Bad Vilbel', countryIso: 'de', region: '', areaCodes: ['6101'] },
  { slug: 'bad-wunnenberg', name: 'Bad Wunnenberg', countryIso: 'de', region: '', areaCodes: ['2957'] },
  { slug: 'baden-baden', name: 'Baden-Baden', countryIso: 'de', region: '', areaCodes: ['7221'] },
  { slug: 'bamberg', name: 'Bamberg', countryIso: 'de', region: '', areaCodes: ['951'] },
  { slug: 'barsinghausen', name: 'Barsinghausen', countryIso: 'de', region: '', areaCodes: ['5105'] },
  { slug: 'bayreuth', name: 'Bayreuth', countryIso: 'de', region: '', areaCodes: ['921'] },
  { slug: 'bensheim', name: 'Bensheim', countryIso: 'de', region: '', areaCodes: ['6251'] },
  { slug: 'bergen-enkheim', name: 'Bergen-Enkheim', countryIso: 'de', region: '', areaCodes: ['6109'] },
  { slug: 'bergheim', name: 'Bergheim', countryIso: 'de', region: '', areaCodes: ['2271'] },
  { slug: 'bergisch-gladbach', name: 'Bergisch Gladbach', countryIso: 'de', region: '', areaCodes: ['2202'] },
  { slug: 'berlin', name: 'Berlin', countryIso: 'de', region: '', areaCodes: ['30'] },
  { slug: 'bernau-bei-berlin', name: 'Bernau bei Berlin', countryIso: 'de', region: '', areaCodes: ['3338'] },
  { slug: 'bernburg', name: 'Bernburg', countryIso: 'de', region: '', areaCodes: ['3471'] },
  { slug: 'bexbach', name: 'Bexbach', countryIso: 'de', region: '', areaCodes: ['6826'] },
  { slug: 'biedenkopf', name: 'Biedenkopf', countryIso: 'de', region: '', areaCodes: ['6461'] },
  { slug: 'biederitz', name: 'Biederitz', countryIso: 'de', region: '', areaCodes: ['39292'] },
  { slug: 'bielefeld', name: 'Bielefeld', countryIso: 'de', region: '', areaCodes: ['521'] },
  { slug: 'bienenbuttel', name: 'Bienenbuttel', countryIso: 'de', region: '', areaCodes: ['5823'] },
  { slug: 'biessenhofen', name: 'Biessenhofen', countryIso: 'de', region: '', areaCodes: ['8341'] },
  { slug: 'billigheim-ingenheim', name: 'Billigheim-Ingenheim', countryIso: 'de', region: '', areaCodes: ['6349'] },
  { slug: 'bilsen', name: 'Bilsen', countryIso: 'de', region: '', areaCodes: ['4106'] },
  { slug: 'bingen-am-rhein', name: 'Bingen am Rhein', countryIso: 'de', region: '', areaCodes: ['6721'] },
  { slug: 'bippen', name: 'Bippen', countryIso: 'de', region: '', areaCodes: ['5435'] },
  { slug: 'bispingen', name: 'Bispingen', countryIso: 'de', region: '', areaCodes: ['5194'] },
  { slug: 'bitterfeld', name: 'Bitterfeld', countryIso: 'de', region: '', areaCodes: ['3493'] },
  { slug: 'blankenfelde-mahlow', name: 'Blankenfelde-Mahlow', countryIso: 'de', region: '', areaCodes: ['3379'] },
  { slug: 'blankenhain', name: 'Blankenhain', countryIso: 'de', region: '', areaCodes: ['36459'] },
  { slug: 'blankenheim-ahr', name: 'Blankenheim Ahr', countryIso: 'de', region: '', areaCodes: ['2449'] },
  { slug: 'blieskastel', name: 'Blieskastel', countryIso: 'de', region: '', areaCodes: ['6842'] },
  { slug: 'boblingen', name: 'Boblingen', countryIso: 'de', region: '', areaCodes: ['7031'] },
  { slug: 'bocholt', name: 'Bocholt', countryIso: 'de', region: '', areaCodes: ['2871'] },
  { slug: 'bochum', name: 'Bochum', countryIso: 'de', region: '', areaCodes: ['234'] },
  { slug: 'bonn', name: 'Bonn', countryIso: 'de', region: '', areaCodes: ['228'] },
  { slug: 'borken', name: 'Borken', countryIso: 'de', region: '', areaCodes: ['2862'] },
  { slug: 'bottrop', name: 'Bottrop', countryIso: 'de', region: '', areaCodes: ['2041'] },
  { slug: 'brackenheim', name: 'Brackenheim', countryIso: 'de', region: '', areaCodes: ['7135'] },
  { slug: 'brandenburg', name: 'Brandenburg', countryIso: 'de', region: '', areaCodes: ['3381'] },
  { slug: 'brandis', name: 'Brandis', countryIso: 'de', region: '', areaCodes: ['3429'] },
  { slug: 'brehna', name: 'Brehna', countryIso: 'de', region: '', areaCodes: ['34954'] },
  { slug: 'breisgau', name: 'Breisgau', countryIso: 'de', region: '', areaCodes: ['9721'] },
  { slug: 'breitbrunn', name: 'Breitbrunn', countryIso: 'de', region: '', areaCodes: ['8054'] },
  { slug: 'bremen', name: 'Bremen', countryIso: 'de', region: '', areaCodes: ['421'] },
  { slug: 'bremerhaven', name: 'Bremerhaven', countryIso: 'de', region: '', areaCodes: ['471'] },
  { slug: 'brilon', name: 'Brilon', countryIso: 'de', region: '', areaCodes: ['2961'] },
  { slug: 'brockel', name: 'Brockel', countryIso: 'de', region: '', areaCodes: ['5144'] },
  { slug: 'broderstorf', name: 'Broderstorf', countryIso: 'de', region: '', areaCodes: ['38204'] },
  { slug: 'bruchsal', name: 'Bruchsal', countryIso: 'de', region: '', areaCodes: ['7251'] },
  { slug: 'bruckmuhl', name: 'Bruckmuhl', countryIso: 'de', region: '', areaCodes: ['8061', '8062'] },
  { slug: 'brunswick', name: 'Brunswick', countryIso: 'de', region: '', areaCodes: ['531'] },
  { slug: 'buchholz-in-der-nordheide', name: 'Buchholz in der Nordheide', countryIso: 'de', region: '', areaCodes: ['4186'] },
  { slug: 'buchlberg', name: 'Buchlberg', countryIso: 'de', region: '', areaCodes: ['8505'] },
  { slug: 'buckeburg', name: 'Buckeburg', countryIso: 'de', region: '', areaCodes: ['5722'] },
  { slug: 'budelsdorf', name: 'Budelsdorf', countryIso: 'de', region: '', areaCodes: ['4331'] },
  { slug: 'buren', name: 'Buren', countryIso: 'de', region: '', areaCodes: ['2951', '2955'] },
  { slug: 'burgstadt', name: 'Burgstadt', countryIso: 'de', region: '', areaCodes: ['9371'] },
  { slug: 'burstadt', name: 'Burstadt', countryIso: 'de', region: '', areaCodes: ['6206'] },
  { slug: 'buseck', name: 'Buseck', countryIso: 'de', region: '', areaCodes: ['6408'] },
  { slug: 'butzbach', name: 'Butzbach', countryIso: 'de', region: '', areaCodes: ['6033'] },
  { slug: 'buxtehude', name: 'Buxtehude', countryIso: 'de', region: '', areaCodes: ['4161'] },
  { slug: 'celle', name: 'Celle', countryIso: 'de', region: '', areaCodes: ['5141'] },
  { slug: 'chemnitz', name: 'Chemnitz', countryIso: 'de', region: '', areaCodes: ['371'] },
  { slug: 'coburg', name: 'Coburg', countryIso: 'de', region: '', areaCodes: ['9561'] },
  { slug: 'cologne', name: 'Cologne', countryIso: 'de', region: '', areaCodes: ['221', '2236'] },
  { slug: 'cologne-porz', name: 'Cologne-Porz', countryIso: 'de', region: '', areaCodes: ['2203'] },
  { slug: 'coswig-anhalt', name: 'Coswig (Anhalt)', countryIso: 'de', region: '', areaCodes: ['34903'] },
  { slug: 'cottbus', name: 'Cottbus', countryIso: 'de', region: '', areaCodes: ['355'] },
  { slug: 'cuxhaven', name: 'Cuxhaven', countryIso: 'de', region: '', areaCodes: ['4721'] },
  { slug: 'dachau', name: 'Dachau', countryIso: 'de', region: '', areaCodes: ['8131'] },
  { slug: 'damp', name: 'Damp', countryIso: 'de', region: '', areaCodes: ['4352'] },
  { slug: 'darmstadt', name: 'Darmstadt', countryIso: 'de', region: '', areaCodes: ['6151'] },
  { slug: 'datteln', name: 'Datteln', countryIso: 'de', region: '', areaCodes: ['2363'] },
  { slug: 'deggendorf', name: 'Deggendorf', countryIso: 'de', region: '', areaCodes: ['991'] },
  { slug: 'delbruck', name: 'Delbruck', countryIso: 'de', region: '', areaCodes: ['5250'] },
  { slug: 'dermbach', name: 'Dermbach', countryIso: 'de', region: '', areaCodes: ['36964'] },
  { slug: 'detmold', name: 'Detmold', countryIso: 'de', region: '', areaCodes: ['5231'] },
  { slug: 'dieburg', name: 'Dieburg', countryIso: 'de', region: '', areaCodes: ['6071'] },
  { slug: 'dillingen-an-der-donau', name: 'Dillingen an der Donau', countryIso: 'de', region: '', areaCodes: ['9071'] },
  { slug: 'ditzingen', name: 'Ditzingen', countryIso: 'de', region: '', areaCodes: ['7156'] },
  { slug: 'dollnstein', name: 'Dollnstein', countryIso: 'de', region: '', areaCodes: ['8422'] },
  { slug: 'donauworth', name: 'Donauworth', countryIso: 'de', region: '', areaCodes: ['906'] },
  { slug: 'dormagen', name: 'Dormagen', countryIso: 'de', region: '', areaCodes: ['2133'] },
  { slug: 'dorsten', name: 'Dorsten', countryIso: 'de', region: '', areaCodes: ['2362'] },
  { slug: 'dortmund', name: 'Dortmund', countryIso: 'de', region: '', areaCodes: ['231'] },
  { slug: 'dreieich', name: 'Dreieich', countryIso: 'de', region: '', areaCodes: ['6103'] },
  { slug: 'dresden', name: 'Dresden', countryIso: 'de', region: '', areaCodes: ['351'] },
  { slug: 'drolshagen-bleche', name: 'Drolshagen-Bleche', countryIso: 'de', region: '', areaCodes: ['2763'] },
  { slug: 'duisburg', name: 'Duisburg', countryIso: 'de', region: '', areaCodes: ['203', '2065'] },
  { slug: 'dulmen', name: 'Dulmen', countryIso: 'de', region: '', areaCodes: ['2594'] },
  { slug: 'duren', name: 'Duren', countryIso: 'de', region: '', areaCodes: ['2421'] },
  { slug: 'dusseldorf', name: 'Dusseldorf', countryIso: 'de', region: '', areaCodes: ['211'] },
  { slug: 'eberfing', name: 'Eberfing', countryIso: 'de', region: '', areaCodes: ['8802'] },
  { slug: 'eichenau', name: 'Eichenau', countryIso: 'de', region: '', areaCodes: ['8141'] },
  { slug: 'eisenach', name: 'Eisenach', countryIso: 'de', region: '', areaCodes: ['3691'] },
  { slug: 'elbingerode', name: 'Elbingerode', countryIso: 'de', region: '', areaCodes: ['39454'] },
  { slug: 'eldingen', name: 'Eldingen', countryIso: 'de', region: '', areaCodes: ['5145'] },
  { slug: 'emden', name: 'Emden', countryIso: 'de', region: '', areaCodes: ['4921'] },
  { slug: 'emmendingen', name: 'Emmendingen', countryIso: 'de', region: '', areaCodes: ['7641'] },
  { slug: 'emmerich-am-rhein', name: 'Emmerich am Rhein', countryIso: 'de', region: '', areaCodes: ['2822', '2828'] },
  { slug: 'emsburen', name: 'Emsburen', countryIso: 'de', region: '', areaCodes: ['5903'] },
  { slug: 'emsdetten', name: 'Emsdetten', countryIso: 'de', region: '', areaCodes: ['2572'] },
  { slug: 'eningen-unter-achalm', name: 'Eningen unter Achalm', countryIso: 'de', region: '', areaCodes: ['7121'] },
  { slug: 'ense', name: 'Ense', countryIso: 'de', region: '', areaCodes: ['2938'] },
  { slug: 'erfurt', name: 'Erfurt', countryIso: 'de', region: '', areaCodes: ['361'] },
  { slug: 'erkelenz', name: 'Erkelenz', countryIso: 'de', region: '', areaCodes: ['2431'] },
  { slug: 'erkner', name: 'Erkner', countryIso: 'de', region: '', areaCodes: ['3362'] },
  { slug: 'erlangen', name: 'Erlangen', countryIso: 'de', region: '', areaCodes: ['9131'] },
  { slug: 'erlenbach', name: 'Erlenbach', countryIso: 'de', region: '', areaCodes: ['7132'] },
  { slug: 'erzenhausen', name: 'Erzenhausen', countryIso: 'de', region: '', areaCodes: ['6374'] },
  { slug: 'eschbach', name: 'Eschbach', countryIso: 'de', region: '', areaCodes: ['7634'] },
  { slug: 'eschborn', name: 'Eschborn', countryIso: 'de', region: '', areaCodes: ['6196'] },
  { slug: 'eschenburg', name: 'Eschenburg', countryIso: 'de', region: '', areaCodes: ['2774'] },
  { slug: 'eschwege', name: 'Eschwege', countryIso: 'de', region: '', areaCodes: ['5651'] },
  { slug: 'eschweiler', name: 'Eschweiler', countryIso: 'de', region: '', areaCodes: ['2403'] },
  { slug: 'essen', name: 'Essen', countryIso: 'de', region: '', areaCodes: ['201', '5434'] },
  { slug: 'essen-kettwig', name: 'Essen-Kettwig', countryIso: 'de', region: '', areaCodes: ['2054'] },
  { slug: 'fahrenzhausen', name: 'Fahrenzhausen', countryIso: 'de', region: '', areaCodes: ['8133'] },
  { slug: 'fehmarn', name: 'Fehmarn', countryIso: 'de', region: '', areaCodes: ['4371'] },
  { slug: 'feldafing', name: 'Feldafing', countryIso: 'de', region: '', areaCodes: ['8157'] },
  { slug: 'filderstadt', name: 'Filderstadt', countryIso: 'de', region: '', areaCodes: ['711'] },
  { slug: 'finsterwalde', name: 'Finsterwalde', countryIso: 'de', region: '', areaCodes: ['3531'] },
  { slug: 'flensburg', name: 'Flensburg', countryIso: 'de', region: '', areaCodes: ['461'] },
  { slug: 'flieden', name: 'Flieden', countryIso: 'de', region: '', areaCodes: ['6669'] },
  { slug: 'forchheim', name: 'Forchheim', countryIso: 'de', region: '', areaCodes: ['9191'] },
  { slug: 'frankenblick', name: 'Frankenblick', countryIso: 'de', region: '', areaCodes: ['3675'] },
  { slug: 'frankfurt', name: 'Frankfurt', countryIso: 'de', region: '', areaCodes: ['6109', '69'] },
  { slug: 'frankfurt-oder', name: 'Frankfurt (Oder)', countryIso: 'de', region: '', areaCodes: ['335'] },
  { slug: 'frechen', name: 'Frechen', countryIso: 'de', region: '', areaCodes: ['2234'] },
  { slug: 'freiburg-im-breisgau', name: 'Freiburg im Breisgau', countryIso: 'de', region: '', areaCodes: ['761'] },
  { slug: 'freudenberg', name: 'Freudenberg', countryIso: 'de', region: '', areaCodes: ['2734'] },
  { slug: 'freudenstadt', name: 'Freudenstadt', countryIso: 'de', region: '', areaCodes: ['7441'] },
  { slug: 'frickingen', name: 'Frickingen', countryIso: 'de', region: '', areaCodes: ['7554'] },
  { slug: 'friedrichshafen', name: 'Friedrichshafen', countryIso: 'de', region: '', areaCodes: ['7541'] },
  { slug: 'fulda', name: 'Fulda', countryIso: 'de', region: '', areaCodes: ['661'] },
  { slug: 'furstenwaldespree', name: 'Furstenwalde/Spree', countryIso: 'de', region: '', areaCodes: ['3361'] },
  { slug: 'gaggenau', name: 'Gaggenau', countryIso: 'de', region: '', areaCodes: ['7225'] },
  { slug: 'gaiberg', name: 'Gaiberg', countryIso: 'de', region: '', areaCodes: ['6223'] },
  { slug: 'gaildorf', name: 'Gaildorf', countryIso: 'de', region: '', areaCodes: ['7971'] },
  { slug: 'gallmersgarten', name: 'Gallmersgarten', countryIso: 'de', region: '', areaCodes: ['9843'] },
  { slug: 'garbsen', name: 'Garbsen', countryIso: 'de', region: '', areaCodes: ['5131'] },
  { slug: 'garmisch-partenkirchen', name: 'Garmisch-Partenkirchen', countryIso: 'de', region: '', areaCodes: ['8821'] },
  { slug: 'gaufelden', name: 'Gaufelden', countryIso: 'de', region: '', areaCodes: ['7032'] },
  { slug: 'gechigen', name: 'Gechigen', countryIso: 'de', region: '', areaCodes: ['7056'] },
  { slug: 'geesthacht', name: 'Geesthacht', countryIso: 'de', region: '', areaCodes: ['4152'] },
  { slug: 'geilenkirchen', name: 'Geilenkirchen', countryIso: 'de', region: '', areaCodes: ['2451'] },
  { slug: 'gelsenkirchen', name: 'Gelsenkirchen', countryIso: 'de', region: '', areaCodes: ['209'] },
  { slug: 'gera', name: 'Gera', countryIso: 'de', region: '', areaCodes: ['365'] },
  { slug: 'geretsried', name: 'Geretsried', countryIso: 'de', region: '', areaCodes: ['8171'] },
  { slug: 'gerlingen', name: 'Gerlingen', countryIso: 'de', region: '', areaCodes: ['7156'] },
  { slug: 'gersfeld', name: 'Gersfeld', countryIso: 'de', region: '', areaCodes: ['6654'] },
  { slug: 'gevelsberg', name: 'Gevelsberg', countryIso: 'de', region: '', areaCodes: ['2332'] },
  { slug: 'giengen', name: 'Giengen', countryIso: 'de', region: '', areaCodes: ['7322'] },
  { slug: 'giessen', name: 'Giessen', countryIso: 'de', region: '', areaCodes: ['641'] },
  { slug: 'gifhorn', name: 'Gifhorn', countryIso: 'de', region: '', areaCodes: ['5371'] },
  { slug: 'gilching', name: 'Gilching', countryIso: 'de', region: '', areaCodes: ['8105'] },
  { slug: 'gnarrenburg', name: 'Gnarrenburg', countryIso: 'de', region: '', areaCodes: ['4763'] },
  { slug: 'goch', name: 'Goch', countryIso: 'de', region: '', areaCodes: ['2823'] },
  { slug: 'goppingen', name: 'Goppingen', countryIso: 'de', region: '', areaCodes: ['7161'] },
  { slug: 'gorlitz', name: 'Gorlitz', countryIso: 'de', region: '', areaCodes: ['3581'] },
  { slug: 'gotteszell', name: 'Gotteszell', countryIso: 'de', region: '', areaCodes: ['9929'] },
  { slug: 'gottingen', name: 'Gottingen', countryIso: 'de', region: '', areaCodes: ['551'] },
  { slug: 'gottmadingen', name: 'Gottmadingen', countryIso: 'de', region: '', areaCodes: ['7731'] },
  { slug: 'grambin', name: 'Grambin', countryIso: 'de', region: '', areaCodes: ['39774'] },
  { slug: 'grebenstein', name: 'Grebenstein', countryIso: 'de', region: '', areaCodes: ['5674'] },
  { slug: 'greifswald', name: 'Greifswald', countryIso: 'de', region: '', areaCodes: ['3834'] },
  { slug: 'grevenbroich', name: 'Grevenbroich', countryIso: 'de', region: '', areaCodes: ['2181'] },
  { slug: 'grimma', name: 'Grimma', countryIso: 'de', region: '', areaCodes: ['34384'] },
  { slug: 'gronau-westphalia', name: 'Gronau (Westphalia)', countryIso: 'de', region: '', areaCodes: ['2562'] },
  { slug: 'gros-schacksdorf-simmersdorf', name: 'Gros Schacksdorf-Simmersdorf', countryIso: 'de', region: '', areaCodes: ['35695'] },
  { slug: 'grosneuhausen', name: 'Grosneuhausen', countryIso: 'de', region: '', areaCodes: ['36372'] },
  { slug: 'grossbeeren', name: 'Grossbeeren', countryIso: 'de', region: '', areaCodes: ['33701'] },
  { slug: 'grosshansdorf', name: 'Grosshansdorf', countryIso: 'de', region: '', areaCodes: ['4102'] },
  { slug: 'grossostheim', name: 'Grossostheim', countryIso: 'de', region: '', areaCodes: ['6026'] },
  { slug: 'grundau', name: 'Grundau', countryIso: 'de', region: '', areaCodes: ['6051'] },
  { slug: 'guben', name: 'Guben', countryIso: 'de', region: '', areaCodes: ['3561'] },
  { slug: 'gummersbach', name: 'Gummersbach', countryIso: 'de', region: '', areaCodes: ['2261'] },
  { slug: 'gunthersdorf', name: 'Gunthersdorf', countryIso: 'de', region: '', areaCodes: ['34638'] },
  { slug: 'gutersloh', name: 'Gutersloh', countryIso: 'de', region: '', areaCodes: ['5241'] },
  { slug: 'hagen', name: 'Hagen', countryIso: 'de', region: '', areaCodes: ['2331'] },
  { slug: 'hahnbach', name: 'Hahnbach', countryIso: 'de', region: '', areaCodes: ['9662'] },
  { slug: 'haiger', name: 'Haiger', countryIso: 'de', region: '', areaCodes: ['2771'] },
  { slug: 'haiming', name: 'Haiming', countryIso: 'de', region: '', areaCodes: ['8678'] },
  { slug: 'haiterbach', name: 'Haiterbach', countryIso: 'de', region: '', areaCodes: ['7456'] },
  { slug: 'halle-saale', name: 'Halle (Saale)', countryIso: 'de', region: '', areaCodes: ['345'] },
  { slug: 'haltern-am-see', name: 'Haltern am See', countryIso: 'de', region: '', areaCodes: ['2364'] },
  { slug: 'hamburg', name: 'Hamburg', countryIso: 'de', region: '', areaCodes: ['40'] },
  { slug: 'hamm', name: 'Hamm', countryIso: 'de', region: '', areaCodes: ['2381'] },
  { slug: 'hammoor', name: 'Hammoor', countryIso: 'de', region: '', areaCodes: ['4532'] },
  { slug: 'hanau', name: 'Hanau', countryIso: 'de', region: '', areaCodes: ['6181'] },
  { slug: 'handewitt', name: 'Handewitt', countryIso: 'de', region: '', areaCodes: ['4608'] },
  { slug: 'hanerau-hademarschen', name: 'Hanerau-Hademarschen', countryIso: 'de', region: '', areaCodes: ['4872'] },
  { slug: 'hannover', name: 'Hannover', countryIso: 'de', region: '', areaCodes: ['511'] },
  { slug: 'haren', name: 'Haren', countryIso: 'de', region: '', areaCodes: ['5932'] },
  { slug: 'harrislee', name: 'Harrislee', countryIso: 'de', region: '', areaCodes: ['461'] },
  { slug: 'hartenholm', name: 'Hartenholm', countryIso: 'de', region: '', areaCodes: ['4195'] },
  { slug: 'hattersheim-am-main', name: 'Hattersheim am Main', countryIso: 'de', region: '', areaCodes: ['6190'] },
  { slug: 'hausham', name: 'Hausham', countryIso: 'de', region: '', areaCodes: ['8026'] },
  { slug: 'havixbeck', name: 'Havixbeck', countryIso: 'de', region: '', areaCodes: ['2507'] },
  { slug: 'hechingen', name: 'Hechingen', countryIso: 'de', region: '', areaCodes: ['7471'] },
  { slug: 'heede', name: 'Heede', countryIso: 'de', region: '', areaCodes: ['4963'] },
  { slug: 'heidelberg', name: 'Heidelberg', countryIso: 'de', region: '', areaCodes: ['6221'] },
  { slug: 'heidenheim', name: 'Heidenheim', countryIso: 'de', region: '', areaCodes: ['7321'] },
  { slug: 'heidenrod', name: 'Heidenrod', countryIso: 'de', region: '', areaCodes: ['6124'] },
  { slug: 'heilbronn-neckar', name: 'Heilbronn (Neckar)', countryIso: 'de', region: '', areaCodes: ['7131'] },
  { slug: 'heinsberg', name: 'Heinsberg', countryIso: 'de', region: '', areaCodes: ['2452'] },
  { slug: 'heitersheim', name: 'Heitersheim', countryIso: 'de', region: '', areaCodes: ['7634'] },
  { slug: 'helmstedt', name: 'Helmstedt', countryIso: 'de', region: '', areaCodes: ['5351'] },
  { slug: 'hemmingen', name: 'Hemmingen', countryIso: 'de', region: '', areaCodes: ['5101', '7150'] },
  { slug: 'hennstedt', name: 'Hennstedt', countryIso: 'de', region: '', areaCodes: ['4836', '4877'] },
  { slug: 'henstedt-ulzburg', name: 'Henstedt-Ulzburg', countryIso: 'de', region: '', areaCodes: ['4193'] },
  { slug: 'herford', name: 'Herford', countryIso: 'de', region: '', areaCodes: ['5221'] },
  { slug: 'heringen-werra', name: 'Heringen (Werra)', countryIso: 'de', region: '', areaCodes: ['6624'] },
  { slug: 'herne', name: 'Herne', countryIso: 'de', region: '', areaCodes: ['2323', '2325'] },
  { slug: 'herrsching-am-ammersee', name: 'Herrsching am Ammersee', countryIso: 'de', region: '', areaCodes: ['8152'] },
  { slug: 'hettenhausen', name: 'Hettenhausen', countryIso: 'de', region: '', areaCodes: ['8441'] },
  { slug: 'hettenleidelheim', name: 'Hettenleidelheim', countryIso: 'de', region: '', areaCodes: ['6351'] },
  { slug: 'heusenstamm', name: 'Heusenstamm', countryIso: 'de', region: '', areaCodes: ['6104'] },
  { slug: 'heusweiler', name: 'Heusweiler', countryIso: 'de', region: '', areaCodes: ['6806'] },
  { slug: 'hilden', name: 'Hilden', countryIso: 'de', region: '', areaCodes: ['2103'] },
  { slug: 'hirschau', name: 'Hirschau', countryIso: 'de', region: '', areaCodes: ['9622'] },
  { slug: 'hochst-im-odenwald', name: 'Hochst im Odenwald', countryIso: 'de', region: '', areaCodes: ['6163'] },
  { slug: 'hohenbrunn', name: 'Hohenbrunn', countryIso: 'de', region: '', areaCodes: ['8102'] },
  { slug: 'holzkirchen', name: 'Holzkirchen', countryIso: 'de', region: '', areaCodes: ['8024'] },
  { slug: 'hopsten', name: 'Hopsten', countryIso: 'de', region: '', areaCodes: ['5458'] },
  { slug: 'horrem-kerpen', name: 'Horrem (Kerpen)', countryIso: 'de', region: '', areaCodes: ['2273'] },
  { slug: 'hoyerswerda', name: 'Hoyerswerda', countryIso: 'de', region: '', areaCodes: ['3571'] },
  { slug: 'hundeshagen', name: 'Hundeshagen', countryIso: 'de', region: '', areaCodes: ['36071'] },
  { slug: 'hunstetten', name: 'Hunstetten', countryIso: 'de', region: '', areaCodes: ['6126'] },
  { slug: 'hurth', name: 'Hurth', countryIso: 'de', region: '', areaCodes: ['2233'] },
  { slug: 'husum', name: 'Husum', countryIso: 'de', region: '', areaCodes: ['4841'] },
  { slug: 'idar-oberstein', name: 'Idar-Oberstein', countryIso: 'de', region: '', areaCodes: ['6781'] },
  { slug: 'immendingen', name: 'Immendingen', countryIso: 'de', region: '', areaCodes: ['7462'] },
  { slug: 'immenstaad-am-bodensee', name: 'Immenstaad am Bodensee', countryIso: 'de', region: '', areaCodes: ['7545'] },
  { slug: 'immenstadt-im-allgau', name: 'Immenstadt im Allgau', countryIso: 'de', region: '', areaCodes: ['8323'] },
  { slug: 'ingelfingen', name: 'Ingelfingen', countryIso: 'de', region: '', areaCodes: ['7940'] },
  { slug: 'ingersheim', name: 'Ingersheim', countryIso: 'de', region: '', areaCodes: ['7142'] },
  { slug: 'ingolstadt', name: 'Ingolstadt', countryIso: 'de', region: '', areaCodes: ['841'] },
  { slug: 'inning-am-ammersee', name: 'Inning am Ammersee', countryIso: 'de', region: '', areaCodes: ['8143'] },
  { slug: 'iserlohn', name: 'Iserlohn', countryIso: 'de', region: '', areaCodes: ['2371'] },
  { slug: 'jade', name: 'Jade', countryIso: 'de', region: '', areaCodes: ['4480'] },
  { slug: 'jena', name: 'Jena', countryIso: 'de', region: '', areaCodes: ['3641'] },
  { slug: 'jesberg', name: 'Jesberg', countryIso: 'de', region: '', areaCodes: ['6695'] },
  { slug: 'juterbog', name: 'Juterbog', countryIso: 'de', region: '', areaCodes: ['3372'] },
  { slug: 'kaiserslautern', name: 'Kaiserslautern', countryIso: 'de', region: '', areaCodes: ['631'] },
  { slug: 'karben', name: 'Karben', countryIso: 'de', region: '', areaCodes: ['6039'] },
  { slug: 'karlsbad', name: 'Karlsbad', countryIso: 'de', region: '', areaCodes: ['7202'] },
  { slug: 'karlsruhe', name: 'Karlsruhe', countryIso: 'de', region: '', areaCodes: ['721'] },
  { slug: 'kassel', name: 'Kassel', countryIso: 'de', region: '', areaCodes: ['561'] },
  { slug: 'kehl', name: 'Kehl', countryIso: 'de', region: '', areaCodes: ['7851'] },
  { slug: 'kelkheim-taunus', name: 'Kelkheim (Taunus)', countryIso: 'de', region: '', areaCodes: ['6195'] },
  { slug: 'kempen', name: 'Kempen', countryIso: 'de', region: '', areaCodes: ['2152'] },
  { slug: 'kempten', name: 'Kempten', countryIso: 'de', region: '', areaCodes: ['831'] },
  { slug: 'kiel', name: 'Kiel', countryIso: 'de', region: '', areaCodes: ['431'] },
  { slug: 'kirchdorf', name: 'Kirchdorf', countryIso: 'de', region: '', areaCodes: ['4273'] },
  { slug: 'kirchheim-hessen', name: 'Kirchheim (Hessen)', countryIso: 'de', region: '', areaCodes: ['6628'] },
  { slug: 'kirchheim-unter-teck', name: 'Kirchheim unter Teck', countryIso: 'de', region: '', areaCodes: ['7021'] },
  { slug: 'kissing', name: 'Kissing', countryIso: 'de', region: '', areaCodes: ['8233'] },
  { slug: 'kleinmachnow', name: 'Kleinmachnow', countryIso: 'de', region: '', areaCodes: ['33203'] },
  { slug: 'klettgau', name: 'Klettgau', countryIso: 'de', region: '', areaCodes: ['7742'] },
  { slug: 'kleve-niederrhein', name: 'Kleve (Niederrhein)', countryIso: 'de', region: '', areaCodes: ['2821'] },
  { slug: 'knittlingen', name: 'Knittlingen', countryIso: 'de', region: '', areaCodes: ['7043'] },
  { slug: 'koblenz', name: 'Koblenz', countryIso: 'de', region: '', areaCodes: ['261'] },
  { slug: 'konigs-wusterhausen', name: 'Konigs Wusterhausen', countryIso: 'de', region: '', areaCodes: ['3375'] },
  { slug: 'konigsbrunn', name: 'Konigsbrunn', countryIso: 'de', region: '', areaCodes: ['8231'] },
  { slug: 'konigstein-im-taunus', name: 'Konigstein im Taunus', countryIso: 'de', region: '', areaCodes: ['6174'] },
  { slug: 'konstanz', name: 'Konstanz', countryIso: 'de', region: '', areaCodes: ['7531'] },
  { slug: 'konz', name: 'Konz', countryIso: 'de', region: '', areaCodes: ['6501'] },
  { slug: 'kornwestheim', name: 'Kornwestheim', countryIso: 'de', region: '', areaCodes: ['7154'] },
  { slug: 'krakow-am-see', name: 'Krakow am See', countryIso: 'de', region: '', areaCodes: ['38457'] },
  { slug: 'krefeld', name: 'Krefeld', countryIso: 'de', region: '', areaCodes: ['2151'] },
  { slug: 'kreuzau', name: 'Kreuzau', countryIso: 'de', region: '', areaCodes: ['2422'] },
  { slug: 'kronach', name: 'Kronach', countryIso: 'de', region: '', areaCodes: ['9261'] },
  { slug: 'kronberg-im-taunus', name: 'Kronberg im Taunus', countryIso: 'de', region: '', areaCodes: ['6173'] },
  { slug: 'kuhlungsborn', name: 'Kuhlungsborn', countryIso: 'de', region: '', areaCodes: ['38293'] },
  { slug: 'kulmbach', name: 'Kulmbach', countryIso: 'de', region: '', areaCodes: ['9221'] },
  { slug: 'kulsheim', name: 'Kulsheim', countryIso: 'de', region: '', areaCodes: ['9345'] },
  { slug: 'kurten', name: 'Kurten', countryIso: 'de', region: '', areaCodes: ['2207', '2268'] },
  { slug: 'kustriner-vorland', name: 'Kustriner Vorland', countryIso: 'de', region: '', areaCodes: ['33479'] },
  { slug: 'ladenburg', name: 'Ladenburg', countryIso: 'de', region: '', areaCodes: ['6203'] },
  { slug: 'landau', name: 'Landau', countryIso: 'de', region: '', areaCodes: ['6341'] },
  { slug: 'landsberg-am-lech', name: 'Landsberg am Lech', countryIso: 'de', region: '', areaCodes: ['8191'] },
  { slug: 'landstuhl', name: 'Landstuhl', countryIso: 'de', region: '', areaCodes: ['6371'] },
  { slug: 'langenau', name: 'Langenau', countryIso: 'de', region: '', areaCodes: ['7345'] },
  { slug: 'langenfeld-rheinland', name: 'Langenfeld (Rheinland)', countryIso: 'de', region: '', areaCodes: ['2173'] },
  { slug: 'langerwehe', name: 'Langerwehe', countryIso: 'de', region: '', areaCodes: ['2423'] },
  { slug: 'lauterbach-hesse', name: 'Lauterbach (Hesse)', countryIso: 'de', region: '', areaCodes: ['6641'] },
  { slug: 'lauterecken', name: 'Lauterecken', countryIso: 'de', region: '', areaCodes: ['6382'] },
  { slug: 'lebach', name: 'Lebach', countryIso: 'de', region: '', areaCodes: ['6881'] },
  { slug: 'leer', name: 'Leer', countryIso: 'de', region: '', areaCodes: ['491'] },
  { slug: 'leimen', name: 'Leimen', countryIso: 'de', region: '', areaCodes: ['6224'] },
  { slug: 'leipzig', name: 'Leipzig', countryIso: 'de', region: '', areaCodes: ['341'] },
  { slug: 'lenzen', name: 'Lenzen', countryIso: 'de', region: '', areaCodes: ['38792'] },
  { slug: 'leonberg', name: 'Leonberg', countryIso: 'de', region: '', areaCodes: ['7152'] },
  { slug: 'leverkusen', name: 'Leverkusen', countryIso: 'de', region: '', areaCodes: ['214', '2171'] },
  { slug: 'lilienthal', name: 'Lilienthal', countryIso: 'de', region: '', areaCodes: ['4298'] },
  { slug: 'limeshain', name: 'Limeshain', countryIso: 'de', region: '', areaCodes: ['6048'] },
  { slug: 'lindau', name: 'Lindau', countryIso: 'de', region: '', areaCodes: ['8382'] },
  { slug: 'lindenberg-im-allgau', name: 'Lindenberg im Allgau', countryIso: 'de', region: '', areaCodes: ['8381'] },
  { slug: 'locknitz', name: 'Locknitz', countryIso: 'de', region: '', areaCodes: ['39754'] },
  { slug: 'lohmar', name: 'Lohmar', countryIso: 'de', region: '', areaCodes: ['2246'] },
  { slug: 'lohme', name: 'Lohme', countryIso: 'de', region: '', areaCodes: ['38302'] },
  { slug: 'lohne', name: 'Lohne', countryIso: 'de', region: '', areaCodes: ['5732'] },
  { slug: 'lohne-oldenburg', name: 'Lohne (Oldenburg)', countryIso: 'de', region: '', areaCodes: ['4442'] },
  { slug: 'lohr-am-main', name: 'Lohr am Main', countryIso: 'de', region: '', areaCodes: ['9352'] },
  { slug: 'lorch', name: 'Lorch', countryIso: 'de', region: '', areaCodes: ['7172'] },
  { slug: 'lorrach', name: 'Lorrach', countryIso: 'de', region: '', areaCodes: ['7621'] },
  { slug: 'loxstedt', name: 'Loxstedt', countryIso: 'de', region: '', areaCodes: ['4744'] },
  { slug: 'lubeck', name: 'Lubeck', countryIso: 'de', region: '', areaCodes: ['451'] },
  { slug: 'ludwigsburg', name: 'Ludwigsburg', countryIso: 'de', region: '', areaCodes: ['7141'] },
  { slug: 'ludwigsfelde', name: 'Ludwigsfelde', countryIso: 'de', region: '', areaCodes: ['3378'] },
  { slug: 'ludwigshafen-am-rhein', name: 'Ludwigshafen am Rhein', countryIso: 'de', region: '', areaCodes: ['621'] },
  { slug: 'luneburg', name: 'Luneburg', countryIso: 'de', region: '', areaCodes: ['4131'] },
  { slug: 'lutterberg', name: 'Lutterberg', countryIso: 'de', region: '', areaCodes: ['5543'] },
  { slug: 'magdeburg', name: 'Magdeburg', countryIso: 'de', region: '', areaCodes: ['391'] },
  { slug: 'magstadt', name: 'Magstadt', countryIso: 'de', region: '', areaCodes: ['7159'] },
  { slug: 'mainz', name: 'Mainz', countryIso: 'de', region: '', areaCodes: ['6131'] },
  { slug: 'malschwitz', name: 'Malschwitz', countryIso: 'de', region: '', areaCodes: ['35932'] },
  { slug: 'mannheim', name: 'Mannheim', countryIso: 'de', region: '', areaCodes: ['621'] },
  { slug: 'marburg', name: 'Marburg', countryIso: 'de', region: '', areaCodes: ['6421'] },
  { slug: 'markkleeberg', name: 'Markkleeberg', countryIso: 'de', region: '', areaCodes: ['34297', '34299'] },
  { slug: 'marktheidenfeld', name: 'Marktheidenfeld', countryIso: 'de', region: '', areaCodes: ['9391'] },
  { slug: 'marktoberdorf', name: 'Marktoberdorf', countryIso: 'de', region: '', areaCodes: ['8342'] },
  { slug: 'marl', name: 'Marl', countryIso: 'de', region: '', areaCodes: ['2365'] },
  { slug: 'marxzell', name: 'Marxzell', countryIso: 'de', region: '', areaCodes: ['7248'] },
  { slug: 'maulburg', name: 'Maulburg', countryIso: 'de', region: '', areaCodes: ['7622'] },
  { slug: 'meerbusch', name: 'Meerbusch', countryIso: 'de', region: '', areaCodes: ['2132', '2159'] },
  { slug: 'meine', name: 'Meine', countryIso: 'de', region: '', areaCodes: ['5304'] },
  { slug: 'memmingen', name: 'Memmingen', countryIso: 'de', region: '', areaCodes: ['8331'] },
  { slug: 'mengen', name: 'Mengen', countryIso: 'de', region: '', areaCodes: ['7572'] },
  { slug: 'merchweiler', name: 'Merchweiler', countryIso: 'de', region: '', areaCodes: ['6825'] },
  { slug: 'messkirch', name: 'Messkirch', countryIso: 'de', region: '', areaCodes: ['7575'] },
  { slug: 'messstetten', name: 'Messstetten', countryIso: 'de', region: '', areaCodes: ['7579'] },
  { slug: 'mettmann', name: 'Mettmann', countryIso: 'de', region: '', areaCodes: ['2104'] },
  { slug: 'metzingen', name: 'Metzingen', countryIso: 'de', region: '', areaCodes: ['7123'] },
  { slug: 'milower-land', name: 'Milower Land', countryIso: 'de', region: '', areaCodes: ['33873'] },
  { slug: 'minden', name: 'Minden', countryIso: 'de', region: '', areaCodes: ['571'] },
  { slug: 'moers', name: 'Moers', countryIso: 'de', region: '', areaCodes: ['2841'] },
  { slug: 'mogglingen', name: 'Mogglingen', countryIso: 'de', region: '', areaCodes: ['7174'] },
  { slug: 'mombris', name: 'Mombris', countryIso: 'de', region: '', areaCodes: ['6029'] },
  { slug: 'monchengladbach', name: 'Monchengladbach', countryIso: 'de', region: '', areaCodes: ['2161', '2166'] },
  { slug: 'montabaur', name: 'Montabaur', countryIso: 'de', region: '', areaCodes: ['2602'] },
  { slug: 'morfelden-walldorf', name: 'Morfelden-Walldorf', countryIso: 'de', region: '', areaCodes: ['6105'] },
  { slug: 'morlenbach', name: 'Morlenbach', countryIso: 'de', region: '', areaCodes: ['6209'] },
  { slug: 'mosbach', name: 'Mosbach', countryIso: 'de', region: '', areaCodes: ['6261'] },
  { slug: 'mossingen', name: 'Mossingen', countryIso: 'de', region: '', areaCodes: ['7473'] },
  { slug: 'muhlenbecker-land', name: 'Muhlenbecker Land', countryIso: 'de', region: '', areaCodes: ['33056'] },
  { slug: 'muhlhausen-ehingen', name: 'Muhlhausen-Ehingen', countryIso: 'de', region: '', areaCodes: ['7733'] },
  { slug: 'muhlheim-am-main', name: 'Muhlheim am Main', countryIso: 'de', region: '', areaCodes: ['6108'] },
  { slug: 'mulheim-an-der-ruhr', name: 'Mulheim an der Ruhr', countryIso: 'de', region: '', areaCodes: ['208'] },
  { slug: 'mullheim', name: 'Mullheim', countryIso: 'de', region: '', areaCodes: ['7631'] },
  { slug: 'mundelsheim', name: 'Mundelsheim', countryIso: 'de', region: '', areaCodes: ['7143'] },
  { slug: 'munich', name: 'Munich', countryIso: 'de', region: '', areaCodes: ['89'] },
  { slug: 'munster', name: 'Munster', countryIso: 'de', region: '', areaCodes: ['251'] },
  { slug: 'muschenbach', name: 'Muschenbach', countryIso: 'de', region: '', areaCodes: ['2662'] },
  { slug: 'nachrodt-wiblingwerde', name: 'Nachrodt-Wiblingwerde', countryIso: 'de', region: '', areaCodes: ['2352'] },
  { slug: 'neckarwestheim', name: 'Neckarwestheim', countryIso: 'de', region: '', areaCodes: ['7133'] },
  { slug: 'nettetal', name: 'Nettetal', countryIso: 'de', region: '', areaCodes: ['2153'] },
  { slug: 'neu-isenburg', name: 'Neu-Isenburg', countryIso: 'de', region: '', areaCodes: ['6102'] },
  { slug: 'neubrandenburg', name: 'Neubrandenburg', countryIso: 'de', region: '', areaCodes: ['395'] },
  { slug: 'neuburg-an-der-donau', name: 'Neuburg an der Donau', countryIso: 'de', region: '', areaCodes: ['8431'] },
  { slug: 'neuenkirchen', name: 'Neuenkirchen', countryIso: 'de', region: '', areaCodes: ['5973'] },
  { slug: 'neuhausen-auf-den-fildern', name: 'Neuhausen auf den Fildern', countryIso: 'de', region: '', areaCodes: ['7158'] },
  { slug: 'neukirchen-vluyn', name: 'Neukirchen-Vluyn', countryIso: 'de', region: '', areaCodes: ['2845'] },
  { slug: 'neumarkt', name: 'Neumarkt', countryIso: 'de', region: '', areaCodes: ['9181'] },
  { slug: 'neumunster', name: 'Neumunster', countryIso: 'de', region: '', areaCodes: ['4321'] },
  { slug: 'neuruppin', name: 'Neuruppin', countryIso: 'de', region: '', areaCodes: ['3391'] },
  { slug: 'neuss', name: 'Neuss', countryIso: 'de', region: '', areaCodes: ['2131'] },
  { slug: 'neustadt-bei-coburg', name: 'Neustadt bei Coburg', countryIso: 'de', region: '', areaCodes: ['9568'] },
  { slug: 'neutraubling', name: 'Neutraubling', countryIso: 'de', region: '', areaCodes: ['9401'] },
  { slug: 'nidda', name: 'Nidda', countryIso: 'de', region: '', areaCodes: ['6043'] },
  { slug: 'nidderau', name: 'Nidderau', countryIso: 'de', region: '', areaCodes: ['6187'] },
  { slug: 'niedernberg', name: 'Niedernberg', countryIso: 'de', region: '', areaCodes: ['6028'] },
  { slug: 'nohfelden', name: 'Nohfelden', countryIso: 'de', region: '', areaCodes: ['6852'] },
  { slug: 'norddeich', name: 'Norddeich', countryIso: 'de', region: '', areaCodes: ['4931'] },
  { slug: 'nordhausen', name: 'Nordhausen', countryIso: 'de', region: '', areaCodes: ['3631'] },
  { slug: 'nordhorn', name: 'Nordhorn', countryIso: 'de', region: '', areaCodes: ['5921'] },
  { slug: 'numbrecht', name: 'Numbrecht', countryIso: 'de', region: '', areaCodes: ['2293'] },
  { slug: 'nuremberg', name: 'Nuremberg', countryIso: 'de', region: '', areaCodes: ['911'] },
  { slug: 'nurtingen', name: 'Nurtingen', countryIso: 'de', region: '', areaCodes: ['7022'] },
  { slug: 'oberding', name: 'Oberding', countryIso: 'de', region: '', areaCodes: ['811'] },
  { slug: 'oberhausen', name: 'Oberhausen', countryIso: 'de', region: '', areaCodes: ['208'] },
  { slug: 'oberhausen-rheinhausen', name: 'Oberhausen-Rheinhausen', countryIso: 'de', region: '', areaCodes: ['7254'] },
  { slug: 'oberlungwitz', name: 'Oberlungwitz', countryIso: 'de', region: '', areaCodes: ['3723'] },
  { slug: 'oberursel', name: 'Oberursel', countryIso: 'de', region: '', areaCodes: ['6171'] },
  { slug: 'oberursel-taunus', name: 'Oberursel Taunus', countryIso: 'de', region: '', areaCodes: ['6171'] },
  { slug: 'ochtrup', name: 'Ochtrup', countryIso: 'de', region: '', areaCodes: ['2553'] },
  { slug: 'odenthal', name: 'Odenthal', countryIso: 'de', region: '', areaCodes: ['2174'] },
  { slug: 'oeslau', name: 'Oeslau', countryIso: 'de', region: '', areaCodes: ['9563'] },
  { slug: 'offenburg', name: 'Offenburg', countryIso: 'de', region: '', areaCodes: ['781'] },
  { slug: 'ohringen', name: 'Ohringen', countryIso: 'de', region: '', areaCodes: ['7941'] },
  { slug: 'olching', name: 'Olching', countryIso: 'de', region: '', areaCodes: ['8142'] },
  { slug: 'oldenburg', name: 'Oldenburg', countryIso: 'de', region: '', areaCodes: ['441'] },
  { slug: 'olpe', name: 'Olpe', countryIso: 'de', region: '', areaCodes: ['2761'] },
  { slug: 'osnabruck', name: 'Osnabruck', countryIso: 'de', region: '', areaCodes: ['541'] },
  { slug: 'ostrach', name: 'Ostrach', countryIso: 'de', region: '', areaCodes: ['7585'] },
  { slug: 'paderborn', name: 'Paderborn', countryIso: 'de', region: '', areaCodes: ['5251', '5254'] },
  { slug: 'pappenheim', name: 'Pappenheim', countryIso: 'de', region: '', areaCodes: ['9143'] },
  { slug: 'parsberg', name: 'Parsberg', countryIso: 'de', region: '', areaCodes: ['9492'] },
  { slug: 'pasewalk', name: 'Pasewalk', countryIso: 'de', region: '', areaCodes: ['3973'] },
  { slug: 'peitz', name: 'Peitz', countryIso: 'de', region: '', areaCodes: ['35601'] },
  { slug: 'penzberg', name: 'Penzberg', countryIso: 'de', region: '', areaCodes: ['8856'] },
  { slug: 'pfaffenhofen-an-der-glonn', name: 'Pfaffenhofen an der Glonn', countryIso: 'de', region: '', areaCodes: ['8134'] },
  { slug: 'pfaffenhofen-an-der-ilm', name: 'Pfaffenhofen an der Ilm', countryIso: 'de', region: '', areaCodes: ['7046'] },
  { slug: 'pforzheim', name: 'Pforzheim', countryIso: 'de', region: '', areaCodes: ['7231'] },
  { slug: 'pfungstadt', name: 'Pfungstadt', countryIso: 'de', region: '', areaCodes: ['6157'] },
  { slug: 'philippsburg', name: 'Philippsburg', countryIso: 'de', region: '', areaCodes: ['7256'] },
  { slug: 'pinneberg', name: 'Pinneberg', countryIso: 'de', region: '', areaCodes: ['4101'] },
  { slug: 'pirmasens', name: 'Pirmasens', countryIso: 'de', region: '', areaCodes: ['6331'] },
  { slug: 'pirna', name: 'Pirna', countryIso: 'de', region: '', areaCodes: ['3501'] },
  { slug: 'plosberg', name: 'Plosberg', countryIso: 'de', region: '', areaCodes: ['9636'] },
  { slug: 'polch', name: 'Polch', countryIso: 'de', region: '', areaCodes: ['2654'] },
  { slug: 'potsdam', name: 'Potsdam', countryIso: 'de', region: '', areaCodes: ['331', '33201'] },
  { slug: 'preetz', name: 'Preetz', countryIso: 'de', region: '', areaCodes: ['4342'] },
  { slug: 'pulheim', name: 'Pulheim', countryIso: 'de', region: '', areaCodes: ['2238'] },
  { slug: 'quickborn', name: 'Quickborn', countryIso: 'de', region: '', areaCodes: ['4106'] },
  { slug: 'radolfzell-am-bodensee', name: 'Radolfzell am Bodensee', countryIso: 'de', region: '', areaCodes: ['7732'] },
  { slug: 'rastatt', name: 'Rastatt', countryIso: 'de', region: '', areaCodes: ['7222'] },
  { slug: 'rastede', name: 'Rastede', countryIso: 'de', region: '', areaCodes: ['4402'] },
  { slug: 'ratingen', name: 'Ratingen', countryIso: 'de', region: '', areaCodes: ['2102'] },
  { slug: 'ravensburg', name: 'Ravensburg', countryIso: 'de', region: '', areaCodes: ['751'] },
  { slug: 'regensburg', name: 'Regensburg', countryIso: 'de', region: '', areaCodes: ['941'] },
  { slug: 'rehlingen-siersburg', name: 'Rehlingen-Siersburg', countryIso: 'de', region: '', areaCodes: ['6835'] },
  { slug: 'remagen', name: 'Remagen', countryIso: 'de', region: '', areaCodes: ['2642'] },
  { slug: 'remagen-rolandseck', name: 'Remagen-Rolandseck', countryIso: 'de', region: '', areaCodes: ['2228'] },
  { slug: 'remscheid', name: 'Remscheid', countryIso: 'de', region: '', areaCodes: ['2191'] },
  { slug: 'rennertshofen', name: 'Rennertshofen', countryIso: 'de', region: '', areaCodes: ['8434'] },
  { slug: 'reutlingen', name: 'Reutlingen', countryIso: 'de', region: '', areaCodes: ['7121'] },
  { slug: 'rheinbach', name: 'Rheinbach', countryIso: 'de', region: '', areaCodes: ['2226'] },
  { slug: 'rheinberg', name: 'Rheinberg', countryIso: 'de', region: '', areaCodes: ['2843'] },
  { slug: 'rheine', name: 'Rheine', countryIso: 'de', region: '', areaCodes: ['5971'] },
  { slug: 'riedstadt', name: 'Riedstadt', countryIso: 'de', region: '', areaCodes: ['6158'] },
  { slug: 'rodenbach', name: 'Rodenbach', countryIso: 'de', region: '', areaCodes: ['6184'] },
  { slug: 'rodermark', name: 'Rodermark', countryIso: 'de', region: '', areaCodes: ['6074'] },
  { slug: 'roding', name: 'Roding', countryIso: 'de', region: '', areaCodes: ['9461'] },
  { slug: 'rommerskirchen', name: 'Rommerskirchen', countryIso: 'de', region: '', areaCodes: ['2183'] },
  { slug: 'rosenheim', name: 'Rosenheim', countryIso: 'de', region: '', areaCodes: ['8031'] },
  { slug: 'rosrath', name: 'Rosrath', countryIso: 'de', region: '', areaCodes: ['2205'] },
  { slug: 'rostock', name: 'Rostock', countryIso: 'de', region: '', areaCodes: ['381'] },
  { slug: 'rotenburg-wumme', name: 'Rotenburg (Wumme)', countryIso: 'de', region: '', areaCodes: ['4261'] },
  { slug: 'rothlein', name: 'Rothlein', countryIso: 'de', region: '', areaCodes: ['9723'] },
  { slug: 'rottweil', name: 'Rottweil', countryIso: 'de', region: '', areaCodes: ['741'] },
  { slug: 'rudersberg', name: 'Rudersberg', countryIso: 'de', region: '', areaCodes: ['7183'] },
  { slug: 'rudesheim-am-rhein', name: 'Rudesheim am Rhein', countryIso: 'de', region: '', areaCodes: ['6722'] },
  { slug: 'ruhen', name: 'Ruhen', countryIso: 'de', region: '', areaCodes: ['5367'] },
  { slug: 'russelsheim', name: 'Russelsheim', countryIso: 'de', region: '', areaCodes: ['6142'] },
  { slug: 'rust', name: 'Rust', countryIso: 'de', region: '', areaCodes: ['7822'] },
  { slug: 'saarbrucken', name: 'Saarbrucken', countryIso: 'de', region: '', areaCodes: ['681'] },
  { slug: 'saarlouis', name: 'Saarlouis', countryIso: 'de', region: '', areaCodes: ['6831'] },
  { slug: 'sachsenheim', name: 'Sachsenheim', countryIso: 'de', region: '', areaCodes: ['7147'] },
  { slug: 'saerbeck', name: 'Saerbeck', countryIso: 'de', region: '', areaCodes: ['2574'] },
  { slug: 'saint-blaise', name: 'Saint Blaise', countryIso: 'de', region: '', areaCodes: ['7672'] },
  { slug: 'sangerhausen', name: 'Sangerhausen', countryIso: 'de', region: '', areaCodes: ['3464'] },
  { slug: 'sasbach', name: 'Sasbach', countryIso: 'de', region: '', areaCodes: ['7841'] },
  { slug: 'sasbach-am-kaiserstuhl', name: 'Sasbach am Kaiserstuhl', countryIso: 'de', region: '', areaCodes: ['7662'] },
  { slug: 'schaafheim', name: 'Schaafheim', countryIso: 'de', region: '', areaCodes: ['6073'] },
  { slug: 'scharbeutz', name: 'Scharbeutz', countryIso: 'de', region: '', areaCodes: ['4524'] },
  { slug: 'schleckheim', name: 'Schleckheim', countryIso: 'de', region: '', areaCodes: ['2408'] },
  { slug: 'schleswig', name: 'Schleswig', countryIso: 'de', region: '', areaCodes: ['4621'] },
  { slug: 'schoffengrund', name: 'Schoffengrund', countryIso: 'de', region: '', areaCodes: ['6445'] },
  { slug: 'schoppenstedt', name: 'Schoppenstedt', countryIso: 'de', region: '', areaCodes: ['5332'] },
  { slug: 'schramberg', name: 'Schramberg', countryIso: 'de', region: '', areaCodes: ['7422'] },
  { slug: 'schwabach', name: 'Schwabach', countryIso: 'de', region: '', areaCodes: ['9122'] },
  { slug: 'schwaben', name: 'Schwaben', countryIso: 'de', region: '', areaCodes: ['8121'] },
  { slug: 'schwalbach', name: 'Schwalbach', countryIso: 'de', region: '', areaCodes: ['6834'] },
  { slug: 'schwalbach-am-taunus', name: 'Schwalbach am Taunus', countryIso: 'de', region: '', areaCodes: ['6196'] },
  { slug: 'schwalmtal-niederrhein', name: 'Schwalmtal Niederrhein', countryIso: 'de', region: '', areaCodes: ['2163'] },
  { slug: 'schwanau', name: 'Schwanau', countryIso: 'de', region: '', areaCodes: ['7824'] },
  { slug: 'schwarzach-am-main', name: 'Schwarzach am Main', countryIso: 'de', region: '', areaCodes: ['9324'] },
  { slug: 'schwarzenberg', name: 'Schwarzenberg', countryIso: 'de', region: '', areaCodes: ['3774'] },
  { slug: 'schwarzheide', name: 'Schwarzheide', countryIso: 'de', region: '', areaCodes: ['35752'] },
  { slug: 'schwentinental', name: 'Schwentinental', countryIso: 'de', region: '', areaCodes: ['4307'] },
  { slug: 'schwerin', name: 'Schwerin', countryIso: 'de', region: '', areaCodes: ['385'] },
  { slug: 'schwetzingen', name: 'Schwetzingen', countryIso: 'de', region: '', areaCodes: ['6202'] },
  { slug: 'seelze', name: 'Seelze', countryIso: 'de', region: '', areaCodes: ['5137'] },
  { slug: 'sehestedt', name: 'Sehestedt', countryIso: 'de', region: '', areaCodes: ['4357'] },
  { slug: 'seinsheim', name: 'Seinsheim', countryIso: 'de', region: '', areaCodes: ['9332'] },
  { slug: 'seligenstadt', name: 'Seligenstadt', countryIso: 'de', region: '', areaCodes: ['6182'] },
  { slug: 'selters-taunus', name: 'Selters (Taunus)', countryIso: 'de', region: '', areaCodes: ['6483'] },
  { slug: 'selters-westerwald', name: 'Selters (Westerwald)', countryIso: 'de', region: '', areaCodes: ['2626'] },
  { slug: 'seubersdorf', name: 'Seubersdorf', countryIso: 'de', region: '', areaCodes: ['9497'] },
  { slug: 'siegburg', name: 'Siegburg', countryIso: 'de', region: '', areaCodes: ['2241'] },
  { slug: 'siegen', name: 'Siegen', countryIso: 'de', region: '', areaCodes: ['271'] },
  { slug: 'sieverstedt', name: 'Sieverstedt', countryIso: 'de', region: '', areaCodes: ['4603'] },
  { slug: 'simmozheim', name: 'Simmozheim', countryIso: 'de', region: '', areaCodes: ['7033'] },
  { slug: 'sindelfingen', name: 'Sindelfingen', countryIso: 'de', region: '', areaCodes: ['7031'] },
  { slug: 'sinzheim', name: 'Sinzheim', countryIso: 'de', region: '', areaCodes: ['7223'] },
  { slug: 'soest', name: 'Soest', countryIso: 'de', region: '', areaCodes: ['2921'] },
  { slug: 'sogel', name: 'Sogel', countryIso: 'de', region: '', areaCodes: ['5952'] },
  { slug: 'solingen', name: 'Solingen', countryIso: 'de', region: '', areaCodes: ['212'] },
  { slug: 'soltau', name: 'Soltau', countryIso: 'de', region: '', areaCodes: ['5191'] },
  { slug: 'sonnenbuhl', name: 'Sonnenbuhl', countryIso: 'de', region: '', areaCodes: ['7128'] },
  { slug: 'spiesen-elversberg', name: 'Spiesen-Elversberg', countryIso: 'de', region: '', areaCodes: ['6821'] },
  { slug: 'spremberg', name: 'Spremberg', countryIso: 'de', region: '', areaCodes: ['3563'] },
  { slug: 'sprockhovel', name: 'Sprockhovel', countryIso: 'de', region: '', areaCodes: ['2324'] },
  { slug: 'stadtilm', name: 'Stadtilm', countryIso: 'de', region: '', areaCodes: ['3629'] },
  { slug: 'stadtlohn', name: 'Stadtlohn', countryIso: 'de', region: '', areaCodes: ['2563'] },
  { slug: 'starnberg', name: 'Starnberg', countryIso: 'de', region: '', areaCodes: ['8151'] },
  { slug: 'stassfurt', name: 'Stassfurt', countryIso: 'de', region: '', areaCodes: ['3925'] },
  { slug: 'staufenberg', name: 'Staufenberg', countryIso: 'de', region: '', areaCodes: ['6406'] },
  { slug: 'stephanskirchen-simssee', name: 'Stephanskirchen (Simssee)', countryIso: 'de', region: '', areaCodes: ['8036'] },
  { slug: 'stolberg', name: 'Stolberg', countryIso: 'de', region: '', areaCodes: ['2402'] },
  { slug: 'stuttgart', name: 'Stuttgart', countryIso: 'de', region: '', areaCodes: ['711'] },
  { slug: 'sulingen', name: 'Sulingen', countryIso: 'de', region: '', areaCodes: ['4271'] },
  { slug: 'sylt', name: 'Sylt', countryIso: 'de', region: '', areaCodes: ['4651'] },
  { slug: 'tappenbeck', name: 'Tappenbeck', countryIso: 'de', region: '', areaCodes: ['5366'] },
  { slug: 'tauberbischofsheim', name: 'Tauberbischofsheim', countryIso: 'de', region: '', areaCodes: ['9341'] },
  { slug: 'tegernsee', name: 'Tegernsee', countryIso: 'de', region: '', areaCodes: ['8022'] },
  { slug: 'teltow', name: 'Teltow', countryIso: 'de', region: '', areaCodes: ['3328'] },
  { slug: 'timmendorfer-strand', name: 'Timmendorfer Strand', countryIso: 'de', region: '', areaCodes: ['4503'] },
  { slug: 'todesfelde', name: 'Todesfelde', countryIso: 'de', region: '', areaCodes: ['4558'] },
  { slug: 'toging-am-inn', name: 'Toging am Inn', countryIso: 'de', region: '', areaCodes: ['8631'] },
  { slug: 'traunstein', name: 'Traunstein', countryIso: 'de', region: '', areaCodes: ['861'] },
  { slug: 'triberg-im-schwarzwald', name: 'Triberg im Schwarzwald', countryIso: 'de', region: '', areaCodes: ['7722'] },
  { slug: 'trier', name: 'Trier', countryIso: 'de', region: '', areaCodes: ['651'] },
  { slug: 'troisdorf', name: 'Troisdorf', countryIso: 'de', region: '', areaCodes: ['2241'] },
  { slug: 'tubingen', name: 'Tubingen', countryIso: 'de', region: '', areaCodes: ['7071'] },
  { slug: 'tutzing', name: 'Tutzing', countryIso: 'de', region: '', areaCodes: ['8158'] },
  { slug: 'uberherrn', name: 'Uberherrn', countryIso: 'de', region: '', areaCodes: ['6836'] },
  { slug: 'uberlingen', name: 'Uberlingen', countryIso: 'de', region: '', areaCodes: ['7551'] },
  { slug: 'uetersen', name: 'Uetersen', countryIso: 'de', region: '', areaCodes: ['4122'] },
  { slug: 'ulm', name: 'Ulm', countryIso: 'de', region: '', areaCodes: ['7305', '731'] },
  { slug: 'ulmen', name: 'Ulmen', countryIso: 'de', region: '', areaCodes: ['2676'] },
  { slug: 'ulrichstein', name: 'Ulrichstein', countryIso: 'de', region: '', areaCodes: ['6645'] },
  { slug: 'undenheim', name: 'Undenheim', countryIso: 'de', region: '', areaCodes: ['6737'] },
  { slug: 'unna', name: 'Unna', countryIso: 'de', region: '', areaCodes: ['2303'] },
  { slug: 'untermeitingen', name: 'Untermeitingen', countryIso: 'de', region: '', areaCodes: ['8232'] },
  { slug: 'urbach', name: 'Urbach', countryIso: 'de', region: '', areaCodes: ['7181'] },
  { slug: 'vechta', name: 'Vechta', countryIso: 'de', region: '', areaCodes: ['4441'] },
  { slug: 'verden-an-der-aller', name: 'Verden an der Aller', countryIso: 'de', region: '', areaCodes: ['4231'] },
  { slug: 'vettelschoss', name: 'Vettelschoss', countryIso: 'de', region: '', areaCodes: ['2645'] },
  { slug: 'vierlinden', name: 'Vierlinden', countryIso: 'de', region: '', areaCodes: ['3346'] },
  { slug: 'villingen-schwenningen', name: 'Villingen-Schwenningen', countryIso: 'de', region: '', areaCodes: ['7720', '7721'] },
  { slug: 'vilsbiburg', name: 'Vilsbiburg', countryIso: 'de', region: '', areaCodes: ['8741'] },
  { slug: 'vilshofen-an-der-donau', name: 'Vilshofen an der Donau', countryIso: 'de', region: '', areaCodes: ['8541'] },
  { slug: 'vohenstrauss', name: 'Vohenstrauss', countryIso: 'de', region: '', areaCodes: ['9651'] },
  { slug: 'wadern', name: 'Wadern', countryIso: 'de', region: '', areaCodes: ['6871'] },
  { slug: 'waiblingen', name: 'Waiblingen', countryIso: 'de', region: '', areaCodes: ['7151'] },
  { slug: 'walldorf', name: 'Walldorf', countryIso: 'de', region: '', areaCodes: ['6227'] },
  { slug: 'walsrode', name: 'Walsrode', countryIso: 'de', region: '', areaCodes: ['5161'] },
  { slug: 'warendorf', name: 'Warendorf', countryIso: 'de', region: '', areaCodes: ['2581'] },
  { slug: 'wedel', name: 'Wedel', countryIso: 'de', region: '', areaCodes: ['4103'] },
  { slug: 'wegberg', name: 'Wegberg', countryIso: 'de', region: '', areaCodes: ['2434'] },
  { slug: 'wehr', name: 'Wehr', countryIso: 'de', region: '', areaCodes: ['7762'] },
  { slug: 'weiden-in-der-oberpfalz', name: 'Weiden in der Oberpfalz', countryIso: 'de', region: '', areaCodes: ['961'] },
  { slug: 'weilbach-florsheim', name: 'Weilbach (Florsheim)', countryIso: 'de', region: '', areaCodes: ['6145'] },
  { slug: 'weilerswist', name: 'Weilerswist', countryIso: 'de', region: '', areaCodes: ['2254'] },
  { slug: 'weilheim', name: 'Weilheim', countryIso: 'de', region: '', areaCodes: ['881'] },
  { slug: 'weilheim-an-der-teck', name: 'Weilheim an der Teck', countryIso: 'de', region: '', areaCodes: ['7023'] },
  { slug: 'weimar', name: 'Weimar', countryIso: 'de', region: '', areaCodes: ['3643'] },
  { slug: 'weinbohla', name: 'Weinbohla', countryIso: 'de', region: '', areaCodes: ['35243'] },
  { slug: 'weinheim', name: 'Weinheim', countryIso: 'de', region: '', areaCodes: ['6201'] },
  { slug: 'weinsberg', name: 'Weinsberg', countryIso: 'de', region: '', areaCodes: ['7134'] },
  { slug: 'weissenburg-in-bayern', name: 'Weissenburg in Bayern', countryIso: 'de', region: '', areaCodes: ['9141'] },
  { slug: 'wenden-brunswick', name: 'Wenden (Brunswick)', countryIso: 'de', region: '', areaCodes: ['5307'] },
  { slug: 'wendlingen-am-neckar', name: 'Wendlingen am Neckar', countryIso: 'de', region: '', areaCodes: ['7024'] },
  { slug: 'werder-havel', name: 'Werder (Havel)', countryIso: 'de', region: '', areaCodes: ['3327'] },
  { slug: 'werl', name: 'Werl', countryIso: 'de', region: '', areaCodes: ['2922'] },
  { slug: 'wertheim', name: 'Wertheim', countryIso: 'de', region: '', areaCodes: ['9342'] },
  { slug: 'wesel', name: 'Wesel', countryIso: 'de', region: '', areaCodes: ['281'] },
  { slug: 'wesseling', name: 'Wesseling', countryIso: 'de', region: '', areaCodes: ['2236'] },
  { slug: 'wetzlar', name: 'Wetzlar', countryIso: 'de', region: '', areaCodes: ['6441'] },
  { slug: 'weyarn', name: 'Weyarn', countryIso: 'de', region: '', areaCodes: ['8020'] },
  { slug: 'wiehl', name: 'Wiehl', countryIso: 'de', region: '', areaCodes: ['2262'] },
  { slug: 'wiesbaden', name: 'Wiesbaden', countryIso: 'de', region: '', areaCodes: ['611'] },
  { slug: 'wiesloch', name: 'Wiesloch', countryIso: 'de', region: '', areaCodes: ['6222'] },
  { slug: 'wietmarschen-lohne', name: 'Wietmarschen-Lohne', countryIso: 'de', region: '', areaCodes: ['5908'] },
  { slug: 'wildeshausen', name: 'Wildeshausen', countryIso: 'de', region: '', areaCodes: ['4431'] },
  { slug: 'windeck', name: 'Windeck', countryIso: 'de', region: '', areaCodes: ['2292'] },
  { slug: 'windorf', name: 'Windorf', countryIso: 'de', region: '', areaCodes: ['8546'] },
  { slug: 'windsbach', name: 'Windsbach', countryIso: 'de', region: '', areaCodes: ['9871'] },
  { slug: 'winterbach', name: 'Winterbach', countryIso: 'de', region: '', areaCodes: ['7181'] },
  { slug: 'wissen', name: 'Wissen', countryIso: 'de', region: '', areaCodes: ['2742'] },
  { slug: 'witten', name: 'Witten', countryIso: 'de', region: '', areaCodes: ['2302'] },
  { slug: 'wolfach', name: 'Wolfach', countryIso: 'de', region: '', areaCodes: ['7834'] },
  { slug: 'wolfenbuttel', name: 'Wolfenbuttel', countryIso: 'de', region: '', areaCodes: ['5331'] },
  { slug: 'wolfsburg', name: 'Wolfsburg', countryIso: 'de', region: '', areaCodes: ['5361'] },
  { slug: 'wolnzach', name: 'Wolnzach', countryIso: 'de', region: '', areaCodes: ['8442'] },
  { slug: 'worms', name: 'Worms', countryIso: 'de', region: '', areaCodes: ['6241'] },
  { slug: 'worrstadt', name: 'Worrstadt', countryIso: 'de', region: '', areaCodes: ['6732'] },
  { slug: 'worth-an-der-donau', name: 'Worth an der Donau', countryIso: 'de', region: '', areaCodes: ['9482'] },
  { slug: 'wunstorf', name: 'Wunstorf', countryIso: 'de', region: '', areaCodes: ['5031'] },
  { slug: 'wuppertal', name: 'Wuppertal', countryIso: 'de', region: '', areaCodes: ['202'] },
  { slug: 'wurselen', name: 'Wurselen', countryIso: 'de', region: '', areaCodes: ['2405'] },
  { slug: 'wurzburg', name: 'Wurzburg', countryIso: 'de', region: '', areaCodes: ['931'] },
  { slug: 'wurzen', name: 'Wurzen', countryIso: 'de', region: '', areaCodes: ['3425'] },
  { slug: 'wustermark', name: 'Wustermark', countryIso: 'de', region: '', areaCodes: ['33234'] },
  { slug: 'zeven', name: 'Zeven', countryIso: 'de', region: '', areaCodes: ['4281'] },
  { slug: 'zittau', name: 'Zittau', countryIso: 'de', region: '', areaCodes: ['3583'] },
  { slug: 'zolling', name: 'Zolling', countryIso: 'de', region: '', areaCodes: ['8167'] },
  { slug: 'zossen', name: 'Zossen', countryIso: 'de', region: '', areaCodes: ['33769', '3377'] },
  { slug: 'zuchering-ingolstadt', name: 'Zuchering (Ingolstadt)', countryIso: 'de', region: '', areaCodes: ['8450'] },
  { slug: 'zweibrucken', name: 'Zweibrucken', countryIso: 'de', region: '', areaCodes: ['6332'] },
  { slug: 'zwenkau', name: 'Zwenkau', countryIso: 'de', region: '', areaCodes: ['34203'] },
];
